// This file was generated by counterfeiter
package fake_bbs

import (
	"sync"
	"time"

	"github.com/cloudfoundry-incubator/runtime-schema/bbs"
	"github.com/cloudfoundry-incubator/runtime-schema/models"
	"github.com/tedsuo/ifrit"
)

type FakeNsyncBBS struct {
	DesireLRPStub        func(models.DesiredLRP) error
	desireLRPMutex       sync.RWMutex
	desireLRPArgsForCall []struct {
		arg1 models.DesiredLRP
	}
	desireLRPReturns struct {
		result1 error
	}
	RemoveDesiredLRPByProcessGuidStub        func(guid string) error
	removeDesiredLRPByProcessGuidMutex       sync.RWMutex
	removeDesiredLRPByProcessGuidArgsForCall []struct {
		guid string
	}
	removeDesiredLRPByProcessGuidReturns struct {
		result1 error
	}
	DesiredLRPsByDomainStub        func(domain string) ([]models.DesiredLRP, error)
	desiredLRPsByDomainMutex       sync.RWMutex
	desiredLRPsByDomainArgsForCall []struct {
		domain string
	}
	desiredLRPsByDomainReturns struct {
		result1 []models.DesiredLRP
		result2 error
	}
	ChangeDesiredLRPStub        func(change models.DesiredLRPChange) error
	changeDesiredLRPMutex       sync.RWMutex
	changeDesiredLRPArgsForCall []struct {
		change models.DesiredLRPChange
	}
	changeDesiredLRPReturns struct {
		result1 error
	}
	BumpFreshnessStub        func(freshness models.Freshness) error
	bumpFreshnessMutex       sync.RWMutex
	bumpFreshnessArgsForCall []struct {
		freshness models.Freshness
	}
	bumpFreshnessReturns struct {
		result1 error
	}
	RequestStopLRPIndexStub        func(processGuid string, stopIndex int) error
	requestStopLRPIndexMutex       sync.RWMutex
	requestStopLRPIndexArgsForCall []struct {
		processGuid string
		stopIndex   int
	}
	requestStopLRPIndexReturns struct {
		result1 error
	}
	NewNsyncBulkerLockStub        func(bulkerID string, interval time.Duration) ifrit.Runner
	newNsyncBulkerLockMutex       sync.RWMutex
	newNsyncBulkerLockArgsForCall []struct {
		bulkerID string
		interval time.Duration
	}
	newNsyncBulkerLockReturns struct {
		result1 ifrit.Runner
	}
	NewNsyncListenerLockStub        func(listenerID string, interval time.Duration) ifrit.Runner
	newNsyncListenerLockMutex       sync.RWMutex
	newNsyncListenerLockArgsForCall []struct {
		listenerID string
		interval   time.Duration
	}
	newNsyncListenerLockReturns struct {
		result1 ifrit.Runner
	}
}

func (fake *FakeNsyncBBS) DesireLRP(arg1 models.DesiredLRP) error {
	fake.desireLRPMutex.Lock()
	fake.desireLRPArgsForCall = append(fake.desireLRPArgsForCall, struct {
		arg1 models.DesiredLRP
	}{arg1})
	fake.desireLRPMutex.Unlock()
	if fake.DesireLRPStub != nil {
		return fake.DesireLRPStub(arg1)
	} else {
		return fake.desireLRPReturns.result1
	}
}

func (fake *FakeNsyncBBS) DesireLRPCallCount() int {
	fake.desireLRPMutex.RLock()
	defer fake.desireLRPMutex.RUnlock()
	return len(fake.desireLRPArgsForCall)
}

func (fake *FakeNsyncBBS) DesireLRPArgsForCall(i int) models.DesiredLRP {
	fake.desireLRPMutex.RLock()
	defer fake.desireLRPMutex.RUnlock()
	return fake.desireLRPArgsForCall[i].arg1
}

func (fake *FakeNsyncBBS) DesireLRPReturns(result1 error) {
	fake.DesireLRPStub = nil
	fake.desireLRPReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNsyncBBS) RemoveDesiredLRPByProcessGuid(guid string) error {
	fake.removeDesiredLRPByProcessGuidMutex.Lock()
	fake.removeDesiredLRPByProcessGuidArgsForCall = append(fake.removeDesiredLRPByProcessGuidArgsForCall, struct {
		guid string
	}{guid})
	fake.removeDesiredLRPByProcessGuidMutex.Unlock()
	if fake.RemoveDesiredLRPByProcessGuidStub != nil {
		return fake.RemoveDesiredLRPByProcessGuidStub(guid)
	} else {
		return fake.removeDesiredLRPByProcessGuidReturns.result1
	}
}

func (fake *FakeNsyncBBS) RemoveDesiredLRPByProcessGuidCallCount() int {
	fake.removeDesiredLRPByProcessGuidMutex.RLock()
	defer fake.removeDesiredLRPByProcessGuidMutex.RUnlock()
	return len(fake.removeDesiredLRPByProcessGuidArgsForCall)
}

func (fake *FakeNsyncBBS) RemoveDesiredLRPByProcessGuidArgsForCall(i int) string {
	fake.removeDesiredLRPByProcessGuidMutex.RLock()
	defer fake.removeDesiredLRPByProcessGuidMutex.RUnlock()
	return fake.removeDesiredLRPByProcessGuidArgsForCall[i].guid
}

func (fake *FakeNsyncBBS) RemoveDesiredLRPByProcessGuidReturns(result1 error) {
	fake.RemoveDesiredLRPByProcessGuidStub = nil
	fake.removeDesiredLRPByProcessGuidReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNsyncBBS) DesiredLRPsByDomain(domain string) ([]models.DesiredLRP, error) {
	fake.desiredLRPsByDomainMutex.Lock()
	fake.desiredLRPsByDomainArgsForCall = append(fake.desiredLRPsByDomainArgsForCall, struct {
		domain string
	}{domain})
	fake.desiredLRPsByDomainMutex.Unlock()
	if fake.DesiredLRPsByDomainStub != nil {
		return fake.DesiredLRPsByDomainStub(domain)
	} else {
		return fake.desiredLRPsByDomainReturns.result1, fake.desiredLRPsByDomainReturns.result2
	}
}

func (fake *FakeNsyncBBS) DesiredLRPsByDomainCallCount() int {
	fake.desiredLRPsByDomainMutex.RLock()
	defer fake.desiredLRPsByDomainMutex.RUnlock()
	return len(fake.desiredLRPsByDomainArgsForCall)
}

func (fake *FakeNsyncBBS) DesiredLRPsByDomainArgsForCall(i int) string {
	fake.desiredLRPsByDomainMutex.RLock()
	defer fake.desiredLRPsByDomainMutex.RUnlock()
	return fake.desiredLRPsByDomainArgsForCall[i].domain
}

func (fake *FakeNsyncBBS) DesiredLRPsByDomainReturns(result1 []models.DesiredLRP, result2 error) {
	fake.DesiredLRPsByDomainStub = nil
	fake.desiredLRPsByDomainReturns = struct {
		result1 []models.DesiredLRP
		result2 error
	}{result1, result2}
}

func (fake *FakeNsyncBBS) ChangeDesiredLRP(change models.DesiredLRPChange) error {
	fake.changeDesiredLRPMutex.Lock()
	fake.changeDesiredLRPArgsForCall = append(fake.changeDesiredLRPArgsForCall, struct {
		change models.DesiredLRPChange
	}{change})
	fake.changeDesiredLRPMutex.Unlock()
	if fake.ChangeDesiredLRPStub != nil {
		return fake.ChangeDesiredLRPStub(change)
	} else {
		return fake.changeDesiredLRPReturns.result1
	}
}

func (fake *FakeNsyncBBS) ChangeDesiredLRPCallCount() int {
	fake.changeDesiredLRPMutex.RLock()
	defer fake.changeDesiredLRPMutex.RUnlock()
	return len(fake.changeDesiredLRPArgsForCall)
}

func (fake *FakeNsyncBBS) ChangeDesiredLRPArgsForCall(i int) models.DesiredLRPChange {
	fake.changeDesiredLRPMutex.RLock()
	defer fake.changeDesiredLRPMutex.RUnlock()
	return fake.changeDesiredLRPArgsForCall[i].change
}

func (fake *FakeNsyncBBS) ChangeDesiredLRPReturns(result1 error) {
	fake.ChangeDesiredLRPStub = nil
	fake.changeDesiredLRPReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNsyncBBS) BumpFreshness(freshness models.Freshness) error {
	fake.bumpFreshnessMutex.Lock()
	fake.bumpFreshnessArgsForCall = append(fake.bumpFreshnessArgsForCall, struct {
		freshness models.Freshness
	}{freshness})
	fake.bumpFreshnessMutex.Unlock()
	if fake.BumpFreshnessStub != nil {
		return fake.BumpFreshnessStub(freshness)
	} else {
		return fake.bumpFreshnessReturns.result1
	}
}

func (fake *FakeNsyncBBS) BumpFreshnessCallCount() int {
	fake.bumpFreshnessMutex.RLock()
	defer fake.bumpFreshnessMutex.RUnlock()
	return len(fake.bumpFreshnessArgsForCall)
}

func (fake *FakeNsyncBBS) BumpFreshnessArgsForCall(i int) models.Freshness {
	fake.bumpFreshnessMutex.RLock()
	defer fake.bumpFreshnessMutex.RUnlock()
	return fake.bumpFreshnessArgsForCall[i].freshness
}

func (fake *FakeNsyncBBS) BumpFreshnessReturns(result1 error) {
	fake.BumpFreshnessStub = nil
	fake.bumpFreshnessReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNsyncBBS) RequestStopLRPIndex(processGuid string, stopIndex int) error {
	fake.requestStopLRPIndexMutex.Lock()
	fake.requestStopLRPIndexArgsForCall = append(fake.requestStopLRPIndexArgsForCall, struct {
		processGuid string
		stopIndex   int
	}{processGuid, stopIndex})
	fake.requestStopLRPIndexMutex.Unlock()
	if fake.RequestStopLRPIndexStub != nil {
		return fake.RequestStopLRPIndexStub(processGuid, stopIndex)
	} else {
		return fake.requestStopLRPIndexReturns.result1
	}
}

func (fake *FakeNsyncBBS) RequestStopLRPIndexCallCount() int {
	fake.requestStopLRPIndexMutex.RLock()
	defer fake.requestStopLRPIndexMutex.RUnlock()
	return len(fake.requestStopLRPIndexArgsForCall)
}

func (fake *FakeNsyncBBS) RequestStopLRPIndexArgsForCall(i int) (string, int) {
	fake.requestStopLRPIndexMutex.RLock()
	defer fake.requestStopLRPIndexMutex.RUnlock()
	return fake.requestStopLRPIndexArgsForCall[i].processGuid, fake.requestStopLRPIndexArgsForCall[i].stopIndex
}

func (fake *FakeNsyncBBS) RequestStopLRPIndexReturns(result1 error) {
	fake.RequestStopLRPIndexStub = nil
	fake.requestStopLRPIndexReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNsyncBBS) NewNsyncBulkerLock(bulkerID string, interval time.Duration) ifrit.Runner {
	fake.newNsyncBulkerLockMutex.Lock()
	fake.newNsyncBulkerLockArgsForCall = append(fake.newNsyncBulkerLockArgsForCall, struct {
		bulkerID string
		interval time.Duration
	}{bulkerID, interval})
	fake.newNsyncBulkerLockMutex.Unlock()
	if fake.NewNsyncBulkerLockStub != nil {
		return fake.NewNsyncBulkerLockStub(bulkerID, interval)
	} else {
		return fake.newNsyncBulkerLockReturns.result1
	}
}

func (fake *FakeNsyncBBS) NewNsyncBulkerLockCallCount() int {
	fake.newNsyncBulkerLockMutex.RLock()
	defer fake.newNsyncBulkerLockMutex.RUnlock()
	return len(fake.newNsyncBulkerLockArgsForCall)
}

func (fake *FakeNsyncBBS) NewNsyncBulkerLockArgsForCall(i int) (string, time.Duration) {
	fake.newNsyncBulkerLockMutex.RLock()
	defer fake.newNsyncBulkerLockMutex.RUnlock()
	return fake.newNsyncBulkerLockArgsForCall[i].bulkerID, fake.newNsyncBulkerLockArgsForCall[i].interval
}

func (fake *FakeNsyncBBS) NewNsyncBulkerLockReturns(result1 ifrit.Runner) {
	fake.NewNsyncBulkerLockStub = nil
	fake.newNsyncBulkerLockReturns = struct {
		result1 ifrit.Runner
	}{result1}
}

func (fake *FakeNsyncBBS) NewNsyncListenerLock(listenerID string, interval time.Duration) ifrit.Runner {
	fake.newNsyncListenerLockMutex.Lock()
	fake.newNsyncListenerLockArgsForCall = append(fake.newNsyncListenerLockArgsForCall, struct {
		listenerID string
		interval   time.Duration
	}{listenerID, interval})
	fake.newNsyncListenerLockMutex.Unlock()
	if fake.NewNsyncListenerLockStub != nil {
		return fake.NewNsyncListenerLockStub(listenerID, interval)
	} else {
		return fake.newNsyncListenerLockReturns.result1
	}
}

func (fake *FakeNsyncBBS) NewNsyncListenerLockCallCount() int {
	fake.newNsyncListenerLockMutex.RLock()
	defer fake.newNsyncListenerLockMutex.RUnlock()
	return len(fake.newNsyncListenerLockArgsForCall)
}

func (fake *FakeNsyncBBS) NewNsyncListenerLockArgsForCall(i int) (string, time.Duration) {
	fake.newNsyncListenerLockMutex.RLock()
	defer fake.newNsyncListenerLockMutex.RUnlock()
	return fake.newNsyncListenerLockArgsForCall[i].listenerID, fake.newNsyncListenerLockArgsForCall[i].interval
}

func (fake *FakeNsyncBBS) NewNsyncListenerLockReturns(result1 ifrit.Runner) {
	fake.NewNsyncListenerLockStub = nil
	fake.newNsyncListenerLockReturns = struct {
		result1 ifrit.Runner
	}{result1}
}

var _ bbs.NsyncBBS = new(FakeNsyncBBS)
