package fake_bbs_test

import (
	_ "github.com/cloudfoundry-incubator/runtime-schema/bbs/fake_bbs"

	. "github.com/onsi/ginkgo"
)

var _ = Describe("FakeBbs", func() {
	// Each fake generated by counterfeiter adds a line like:
	//
	//   var _ mypackage.MyInterface = new(FakeMyInterface)
	//
	// By "_"-immporting the fake_bbs package, this test suite will fail to
	// compile unless the fakes implement the interfaces they're supposed to.

	It("Has fakes that implement the interfaces they're supposed to", func() {})
})
