#!/bin/bash
# vim: set ft=sh

set -e -x

FIRST_GOPATH=`echo $GOPATH | cut -d':' -f1`

export PATH=$FIRST_GOPATH/bin:$PATH

go get -v github.com/vito/gocart

gocart
go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -i -skipMeasurements -randomizeAllSpecs "$@"
