// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/runtime-schema/cb"
	"github.com/cloudfoundry-incubator/runtime-schema/models"
)

type FakeAuctioneerClient struct {
	RequestLRPAuctionsStub        func(auctioneerURL string, lrpStart []models.LRPStartRequest) error
	requestLRPAuctionsMutex       sync.RWMutex
	requestLRPAuctionsArgsForCall []struct {
		auctioneerURL string
		lrpStart      []models.LRPStartRequest
	}
	requestLRPAuctionsReturns struct {
		result1 error
	}
}

func (fake *FakeAuctioneerClient) RequestLRPAuctions(auctioneerURL string, lrpStart []models.LRPStartRequest) error {
	fake.requestLRPAuctionsMutex.Lock()
	fake.requestLRPAuctionsArgsForCall = append(fake.requestLRPAuctionsArgsForCall, struct {
		auctioneerURL string
		lrpStart      []models.LRPStartRequest
	}{auctioneerURL, lrpStart})
	fake.requestLRPAuctionsMutex.Unlock()
	if fake.RequestLRPAuctionsStub != nil {
		return fake.RequestLRPAuctionsStub(auctioneerURL, lrpStart)
	} else {
		return fake.requestLRPAuctionsReturns.result1
	}
}

func (fake *FakeAuctioneerClient) RequestLRPAuctionsCallCount() int {
	fake.requestLRPAuctionsMutex.RLock()
	defer fake.requestLRPAuctionsMutex.RUnlock()
	return len(fake.requestLRPAuctionsArgsForCall)
}

func (fake *FakeAuctioneerClient) RequestLRPAuctionsArgsForCall(i int) (string, []models.LRPStartRequest) {
	fake.requestLRPAuctionsMutex.RLock()
	defer fake.requestLRPAuctionsMutex.RUnlock()
	return fake.requestLRPAuctionsArgsForCall[i].auctioneerURL, fake.requestLRPAuctionsArgsForCall[i].lrpStart
}

func (fake *FakeAuctioneerClient) RequestLRPAuctionsReturns(result1 error) {
	fake.RequestLRPAuctionsStub = nil
	fake.requestLRPAuctionsReturns = struct {
		result1 error
	}{result1}
}

var _ cb.AuctioneerClient = new(FakeAuctioneerClient)
