// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/runtime-schema/cb"
	"github.com/cloudfoundry-incubator/runtime-schema/models"
)

type FakeAuctioneerClient struct {
	RequestLRPStartAuctionStub        func(auctioneerURL string, lrpStart models.LRPStart) error
	requestLRPStartAuctionMutex       sync.RWMutex
	requestLRPStartAuctionArgsForCall []struct {
		auctioneerURL string
		lrpStart      models.LRPStart
	}
	requestLRPStartAuctionReturns struct {
		result1 error
	}
	RequestTaskAuctionsStub        func(auctioneerURL string, tasks []models.Task) error
	requestTaskAuctionsMutex       sync.RWMutex
	requestTaskAuctionsArgsForCall []struct {
		auctioneerURL string
		tasks         []models.Task
	}
	requestTaskAuctionsReturns struct {
		result1 error
	}
}

func (fake *FakeAuctioneerClient) RequestLRPStartAuction(auctioneerURL string, lrpStart models.LRPStart) error {
	fake.requestLRPStartAuctionMutex.Lock()
	fake.requestLRPStartAuctionArgsForCall = append(fake.requestLRPStartAuctionArgsForCall, struct {
		auctioneerURL string
		lrpStart      models.LRPStart
	}{auctioneerURL, lrpStart})
	fake.requestLRPStartAuctionMutex.Unlock()
	if fake.RequestLRPStartAuctionStub != nil {
		return fake.RequestLRPStartAuctionStub(auctioneerURL, lrpStart)
	} else {
		return fake.requestLRPStartAuctionReturns.result1
	}
}

func (fake *FakeAuctioneerClient) RequestLRPStartAuctionCallCount() int {
	fake.requestLRPStartAuctionMutex.RLock()
	defer fake.requestLRPStartAuctionMutex.RUnlock()
	return len(fake.requestLRPStartAuctionArgsForCall)
}

func (fake *FakeAuctioneerClient) RequestLRPStartAuctionArgsForCall(i int) (string, models.LRPStart) {
	fake.requestLRPStartAuctionMutex.RLock()
	defer fake.requestLRPStartAuctionMutex.RUnlock()
	return fake.requestLRPStartAuctionArgsForCall[i].auctioneerURL, fake.requestLRPStartAuctionArgsForCall[i].lrpStart
}

func (fake *FakeAuctioneerClient) RequestLRPStartAuctionReturns(result1 error) {
	fake.RequestLRPStartAuctionStub = nil
	fake.requestLRPStartAuctionReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuctioneerClient) RequestTaskAuctions(auctioneerURL string, tasks []models.Task) error {
	fake.requestTaskAuctionsMutex.Lock()
	fake.requestTaskAuctionsArgsForCall = append(fake.requestTaskAuctionsArgsForCall, struct {
		auctioneerURL string
		tasks         []models.Task
	}{auctioneerURL, tasks})
	fake.requestTaskAuctionsMutex.Unlock()
	if fake.RequestTaskAuctionsStub != nil {
		return fake.RequestTaskAuctionsStub(auctioneerURL, tasks)
	} else {
		return fake.requestTaskAuctionsReturns.result1
	}
}

func (fake *FakeAuctioneerClient) RequestTaskAuctionsCallCount() int {
	fake.requestTaskAuctionsMutex.RLock()
	defer fake.requestTaskAuctionsMutex.RUnlock()
	return len(fake.requestTaskAuctionsArgsForCall)
}

func (fake *FakeAuctioneerClient) RequestTaskAuctionsArgsForCall(i int) (string, []models.Task) {
	fake.requestTaskAuctionsMutex.RLock()
	defer fake.requestTaskAuctionsMutex.RUnlock()
	return fake.requestTaskAuctionsArgsForCall[i].auctioneerURL, fake.requestTaskAuctionsArgsForCall[i].tasks
}

func (fake *FakeAuctioneerClient) RequestTaskAuctionsReturns(result1 error) {
	fake.RequestTaskAuctionsStub = nil
	fake.requestTaskAuctionsReturns = struct {
		result1 error
	}{result1}
}

var _ cb.AuctioneerClient = new(FakeAuctioneerClient)
