// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/runtime-schema/cb"
	"github.com/cloudfoundry-incubator/runtime-schema/models"
)

type FakeTaskClient struct {
	CompleteTasksStub        func(receptorURL string, tasks []models.Task) error
	completeTasksMutex       sync.RWMutex
	completeTasksArgsForCall []struct {
		receptorURL string
		tasks       []models.Task
	}
	completeTasksReturns struct {
		result1 error
	}
}

func (fake *FakeTaskClient) CompleteTasks(receptorURL string, tasks []models.Task) error {
	fake.completeTasksMutex.Lock()
	fake.completeTasksArgsForCall = append(fake.completeTasksArgsForCall, struct {
		receptorURL string
		tasks       []models.Task
	}{receptorURL, tasks})
	fake.completeTasksMutex.Unlock()
	if fake.CompleteTasksStub != nil {
		return fake.CompleteTasksStub(receptorURL, tasks)
	} else {
		return fake.completeTasksReturns.result1
	}
}

func (fake *FakeTaskClient) CompleteTasksCallCount() int {
	fake.completeTasksMutex.RLock()
	defer fake.completeTasksMutex.RUnlock()
	return len(fake.completeTasksArgsForCall)
}

func (fake *FakeTaskClient) CompleteTasksArgsForCall(i int) (string, []models.Task) {
	fake.completeTasksMutex.RLock()
	defer fake.completeTasksMutex.RUnlock()
	return fake.completeTasksArgsForCall[i].receptorURL, fake.completeTasksArgsForCall[i].tasks
}

func (fake *FakeTaskClient) CompleteTasksReturns(result1 error) {
	fake.CompleteTasksStub = nil
	fake.completeTasksReturns = struct {
		result1 error
	}{result1}
}

var _ cb.TaskClient = new(FakeTaskClient)
