// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/runtime-schema/cb"
	"github.com/cloudfoundry-incubator/runtime-schema/models"
)

type FakeAuctioneerClient struct {
	RequestLRPStartAuctionsStub        func(auctioneerURL string, lrpStart []models.LRPStart) error
	requestLRPStartAuctionsMutex       sync.RWMutex
	requestLRPStartAuctionsArgsForCall []struct {
		auctioneerURL string
		lrpStart      []models.LRPStart
	}
	requestLRPStartAuctionsReturns struct {
		result1 error
	}
	RequestTaskAuctionsStub        func(auctioneerURL string, tasks []models.Task) error
	requestTaskAuctionsMutex       sync.RWMutex
	requestTaskAuctionsArgsForCall []struct {
		auctioneerURL string
		tasks         []models.Task
	}
	requestTaskAuctionsReturns struct {
		result1 error
	}
}

func (fake *FakeAuctioneerClient) RequestLRPStartAuctions(auctioneerURL string, lrpStart []models.LRPStart) error {
	fake.requestLRPStartAuctionsMutex.Lock()
	fake.requestLRPStartAuctionsArgsForCall = append(fake.requestLRPStartAuctionsArgsForCall, struct {
		auctioneerURL string
		lrpStart      []models.LRPStart
	}{auctioneerURL, lrpStart})
	fake.requestLRPStartAuctionsMutex.Unlock()
	if fake.RequestLRPStartAuctionsStub != nil {
		return fake.RequestLRPStartAuctionsStub(auctioneerURL, lrpStart)
	} else {
		return fake.requestLRPStartAuctionsReturns.result1
	}
}

func (fake *FakeAuctioneerClient) RequestLRPStartAuctionsCallCount() int {
	fake.requestLRPStartAuctionsMutex.RLock()
	defer fake.requestLRPStartAuctionsMutex.RUnlock()
	return len(fake.requestLRPStartAuctionsArgsForCall)
}

func (fake *FakeAuctioneerClient) RequestLRPStartAuctionsArgsForCall(i int) (string, []models.LRPStart) {
	fake.requestLRPStartAuctionsMutex.RLock()
	defer fake.requestLRPStartAuctionsMutex.RUnlock()
	return fake.requestLRPStartAuctionsArgsForCall[i].auctioneerURL, fake.requestLRPStartAuctionsArgsForCall[i].lrpStart
}

func (fake *FakeAuctioneerClient) RequestLRPStartAuctionsReturns(result1 error) {
	fake.RequestLRPStartAuctionsStub = nil
	fake.requestLRPStartAuctionsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuctioneerClient) RequestTaskAuctions(auctioneerURL string, tasks []models.Task) error {
	fake.requestTaskAuctionsMutex.Lock()
	fake.requestTaskAuctionsArgsForCall = append(fake.requestTaskAuctionsArgsForCall, struct {
		auctioneerURL string
		tasks         []models.Task
	}{auctioneerURL, tasks})
	fake.requestTaskAuctionsMutex.Unlock()
	if fake.RequestTaskAuctionsStub != nil {
		return fake.RequestTaskAuctionsStub(auctioneerURL, tasks)
	} else {
		return fake.requestTaskAuctionsReturns.result1
	}
}

func (fake *FakeAuctioneerClient) RequestTaskAuctionsCallCount() int {
	fake.requestTaskAuctionsMutex.RLock()
	defer fake.requestTaskAuctionsMutex.RUnlock()
	return len(fake.requestTaskAuctionsArgsForCall)
}

func (fake *FakeAuctioneerClient) RequestTaskAuctionsArgsForCall(i int) (string, []models.Task) {
	fake.requestTaskAuctionsMutex.RLock()
	defer fake.requestTaskAuctionsMutex.RUnlock()
	return fake.requestTaskAuctionsArgsForCall[i].auctioneerURL, fake.requestTaskAuctionsArgsForCall[i].tasks
}

func (fake *FakeAuctioneerClient) RequestTaskAuctionsReturns(result1 error) {
	fake.RequestTaskAuctionsStub = nil
	fake.requestTaskAuctionsReturns = struct {
		result1 error
	}{result1}
}

var _ cb.AuctioneerClient = new(FakeAuctioneerClient)
