// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/runtime-schema/cell_client"
	"github.com/cloudfoundry-incubator/runtime-schema/models"
)

type FakeClient struct {
	StopLRPInstanceStub        func(cellAddr string, stopInstance models.StopLRPInstance)
	stopLRPInstanceMutex       sync.RWMutex
	stopLRPInstanceArgsForCall []struct {
		cellAddr     string
		stopInstance models.StopLRPInstance
	}
}

func (fake *FakeClient) StopLRPInstance(cellAddr string, stopInstance models.StopLRPInstance) {
	fake.stopLRPInstanceMutex.Lock()
	fake.stopLRPInstanceArgsForCall = append(fake.stopLRPInstanceArgsForCall, struct {
		cellAddr     string
		stopInstance models.StopLRPInstance
	}{cellAddr, stopInstance})
	fake.stopLRPInstanceMutex.Unlock()
	if fake.StopLRPInstanceStub != nil {
		fake.StopLRPInstanceStub(cellAddr, stopInstance)
	}
}

func (fake *FakeClient) StopLRPInstanceCallCount() int {
	fake.stopLRPInstanceMutex.RLock()
	defer fake.stopLRPInstanceMutex.RUnlock()
	return len(fake.stopLRPInstanceArgsForCall)
}

func (fake *FakeClient) StopLRPInstanceArgsForCall(i int) (string, models.StopLRPInstance) {
	fake.stopLRPInstanceMutex.RLock()
	defer fake.stopLRPInstanceMutex.RUnlock()
	return fake.stopLRPInstanceArgsForCall[i].cellAddr, fake.stopLRPInstanceArgsForCall[i].stopInstance
}

var _ cell_client.Client = new(FakeClient)
